Repository nodak-v2/Nodak-Server, pull requests merged in 2024-07, with the labels that each got.

#122 유저 조회 뱃지 응답 포맷 변경
  src/main/java/com/server/nodak/domain/user/dto/BadgeResponse.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoDTO.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
Labels: refactor

#124 좋아요 데이터에 대한 중복 등록/취소 시 응답 코드 수정
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/main/java/com/server/nodak/exception/common/ConflictException.java
Labels: refactor

#126 fix : 팔로우 조회 API 팔로잉 여부 필드 null 응답 이슈
  src/main/java/com/server/nodak/domain/follow/controller/FollowController.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepository.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/server/nodak/domain/follow/service/FollowService.java
  src/main/java/com/server/nodak/domain/notification/service/NotificationService.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoDTO.java
  src/test/java/com/server/nodak/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/server/nodak/domain/follow/service/FollowServiceTest.java
Labels: fix

#128 fix : 투표 정상 종료 이슈
  src/main/java/com/server/nodak/domain/vote/repository/vote/VoteRepository.java
  src/main/java/com/server/nodak/global/service/SchedulerService.java
Labels: 버그

#132 사용자별 알림 API 구현
  src/main/java/com/server/nodak/domain/follow/controller/FollowController.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/server/nodak/domain/follow/service/FollowService.java
  src/main/java/com/server/nodak/domain/notification/controller/NotificationController.java
  src/main/java/com/server/nodak/domain/notification/dto/NotificationInfo.java
  src/main/java/com/server/nodak/domain/notification/entity/Notification.java
  src/main/java/com/server/nodak/domain/notification/repository/NotificationRepository.java
  src/main/java/com/server/nodak/domain/notification/service/NotificationService.java
  src/main/java/com/server/nodak/domain/post/controller/PostController.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/test/java/com/server/nodak/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/server/nodak/domain/follow/service/FollowServiceTest.java
Labels: 기능 구현, refactor
