Repository nodak-v2/Nodak-Server, pull requests merged in 2024-06, with the labels that each got.

#66 CORS 에러 해결을 위한 Config 클래스 생성
  src/main/java/com/server/nodak/config/CorsConfig.java
Labels: fix

#68 refactor : Post 리스트 조회 API 리팩토링
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/dto/PostSearchResponse.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/test/java/com/server/nodak/domain/post/repository/PostRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
Labels: 테스트, refactor

#69 feat : 유저 정보 조회 및 유저 정보 업데이트 기능 구현
  src/main/java/com/server/nodak/domain/follow/domain/Follow.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowJpaRepository.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepository.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/server/nodak/domain/user/controller/UserController.java
  src/main/java/com/server/nodak/domain/user/dto/CurrentUserInfoResponse.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
  src/main/java/com/server/nodak/domain/user/dto/UserUpdateDTO.java
  src/main/java/com/server/nodak/domain/user/service/UserService.java
  src/test/java/com/server/nodak/domain/user/service/UserServiceTest.java
Labels: 기능 구현

#73 refactor : Comment, Post ResponseDto createdAd 필드 포맷팅
  src/main/java/com/server/nodak/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/server/nodak/domain/post/dto/PostResponse.java
Labels: refactor

#78 refactor : CommentResponse 수정
  src/main/java/com/server/nodak/domain/comment/dto/response/CommentResponse.java
Labels: refactor

#79 fix : CommentResponse nickname 하드 코드 삭제 (#77)
  src/main/java/com/server/nodak/domain/comment/dto/response/CommentResponse.java
Labels: fix

#80 fix : 팔로우 조회 로직 수정
  src/main/java/com/server/nodak/domain/follow/repository/FollowJpaRepository.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
Labels: fix

#76 Follow API 구현
  src/main/java/com/server/nodak/domain/follow/controller/FollowController.java
  src/main/java/com/server/nodak/domain/follow/domain/Follow.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowJpaRepository.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepository.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/server/nodak/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/server/nodak/domain/follow/service/FollowService.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
  src/test/java/com/server/nodak/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/server/nodak/domain/follow/service/FollowServiceTest.java
Labels: 기능 구현, 테스트

#81 fix: 테스트코드 에러 수정
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
  src/test/java/com/server/nodak/domain/follow/service/FollowServiceTest.java
Labels: fix, 테스트

#82 SSE(Server Sent Events) 를 통한 알림 기능 구현
  src/main/java/com/server/nodak/domain/notification/controller/NotificationController.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
Labels: 기능 구현

#85 [feat] 채팅 기능을 위한 채팅방 REST API를 구현합니다.
  build.gradle
  src/main/java/com/server/nodak/domain/chat/controller/ChatController.java
  src/main/java/com/server/nodak/domain/chat/domain/ChatRoom.java
  src/main/java/com/server/nodak/domain/chat/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/server/nodak/domain/chat/dto/response/ChatRoomListResponse.java
  src/main/java/com/server/nodak/domain/chat/repository/ChatRoomCustomRepository.java
  src/main/java/com/server/nodak/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/server/nodak/domain/chat/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/server/nodak/domain/chat/service/ChatService.java
  src/test/java/com/server/nodak/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/server/nodak/domain/chat/service/ChatServiceTest.java
Labels: 기능 구현, 테스트

#87 채팅 기능 구현
  src/main/java/com/server/nodak/domain/chat/controller/ChatController.java
  src/main/java/com/server/nodak/domain/chat/domain/Message.java
  src/main/java/com/server/nodak/domain/chat/dto/request/MessageRequest.java
  src/main/java/com/server/nodak/domain/chat/dto/response/MessageResponse.java
  src/main/java/com/server/nodak/domain/chat/repository/MessageRepository.java
  src/main/java/com/server/nodak/domain/chat/service/ChatService.java
  src/main/java/com/server/nodak/global/config/StompConfig.java
  src/main/java/com/server/nodak/global/config/WebSocketInterceptor.java
  src/test/java/com/server/nodak/domain/chat/repository/MessageRepositoryTest.java
  src/test/java/com/server/nodak/domain/chat/service/ChatServiceTest.java
Labels: 기능 구현, 테스트

#89 [feat] 잔디밭 기능 구현
  src/main/java/com/server/nodak/NodakApplication.java
  src/main/java/com/server/nodak/domain/comment/service/CommentService.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/main/java/com/server/nodak/domain/user/controller/UserController.java
  src/main/java/com/server/nodak/domain/user/domain/UserHistory.java
  src/main/java/com/server/nodak/domain/user/dto/UserHistoryListResponse.java
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
  src/main/java/com/server/nodak/domain/user/repository/UserHistoryRepository.java
  src/main/java/com/server/nodak/domain/user/service/UserService.java
  src/main/java/com/server/nodak/domain/vote/service/VoteService.java
  src/main/java/com/server/nodak/global/service/SchedulerService.java
  src/main/java/com/server/nodak/security/aop/IncreaseUserHistory.java
  src/main/java/com/server/nodak/security/aop/UserHistoryAspect.java
  src/test/java/com/server/nodak/domain/user/repository/UserHistoryRepositoryTest.java
Labels: 기능 구현, 테스트

#91 [perform] 삭제 스케줄링 성능 최적화
  src/main/java/com/server/nodak/domain/user/repository/UserHistoryRepository.java
  src/main/java/com/server/nodak/global/service/SchedulerService.java
  src/test/java/com/server/nodak/global/service/SchedulerServiceTest.java
Labels: 테스트, 성능최적화

#93 fix : authorization 어노테이션 수정
  src/main/java/com/server/nodak/domain/user/controller/UserController.java
  src/main/java/com/server/nodak/exception/common/AuthorizationException.java
  src/main/java/com/server/nodak/global/common/response/ApiResponse.java
  src/main/java/com/server/nodak/security/aop/AuthorizationInterceptor.java
  src/main/java/com/server/nodak/security/aop/AuthorizationRequired.java
  src/test/java/com/server/nodak/security/aop/AuthorizationInterceptorTest.java
Labels: fix

#96 [feat] 참여 게시글 리스트 조회 API 구현
  src/main/java/com/server/nodak/domain/post/controller/PostController.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepository.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/test/java/com/server/nodak/domain/post/repository/PostRepositoryImplTest.java
Labels: refactor

#100 투표 도메인 전반 리팩토링, 기능 추가
  src/main/java/com/server/nodak/domain/post/controller/PostController.java
  src/main/java/com/server/nodak/domain/post/dto/PostRequest.java
  src/main/java/com/server/nodak/domain/post/dto/PostSearchResponse.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/main/java/com/server/nodak/domain/vote/controller/VoteController.java
  src/main/java/com/server/nodak/domain/vote/domain/Vote.java
  src/main/java/com/server/nodak/domain/vote/domain/VoteOption.java
Labels: 기능 구현, refactor

#103 대댓글 기능 추가
  src/main/java/com/server/nodak/domain/comment/domain/Comment.java
  src/main/java/com/server/nodak/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentQueryRepository.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentRepository.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/server/nodak/domain/comment/service/CommentService.java
  src/main/java/com/server/nodak/domain/reply/controller/ReplyController.java
  src/main/java/com/server/nodak/domain/reply/dto/CreateReplyRequest.java
  src/main/java/com/server/nodak/domain/reply/dto/DeleteReplyRequest.java
  src/main/java/com/server/nodak/domain/reply/dto/MyCommentHistory.java
  src/main/java/com/server/nodak/domain/reply/dto/MyReplyHistory.java
  src/main/java/com/server/nodak/domain/reply/dto/ReplyResponse.java
  src/main/java/com/server/nodak/domain/reply/entity/Reply.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyJpaRepository.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyRepository.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyRepositoryImpl.java
  src/main/java/com/server/nodak/domain/reply/service/ReplyService.java
  src/test/java/com/server/nodak/domain/comment/service/CommentServiceTest.java
  src/test/java/com/server/nodak/domain/post/repository/PostRepositoryImplTest.java
Labels: 기능 구현, refactor

#105 게시글 생성 시 이미지 RequestBody 수정
  src/main/java/com/server/nodak/domain/post/dto/PostRequest.java
  src/main/java/com/server/nodak/domain/post/dto/VoteOptionRequest.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/main/java/com/server/nodak/domain/vote/domain/VoteOption.java
  src/test/java/com/server/nodak/domain/post/controller/PostControllerTest.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
  src/test/java/com/server/nodak/domain/vote/utils/Utils.java
Labels: refactor

#107 [feat] 로그아웃 API 구현
  src/main/java/com/server/nodak/domain/user/controller/UserController.java
  src/main/java/com/server/nodak/domain/user/service/UserService.java
  src/test/java/com/server/nodak/domain/user/service/UserServiceTest.java
Labels: 기능 구현

#109 투표 조회 API ResponseBody 투표 후보지 이미지 필드 추가
  src/main/java/com/server/nodak/domain/vote/dto/VoteOptionResult.java
  src/main/java/com/server/nodak/domain/vote/repository/vote/VoteRepositoryImpl.java
Labels: refactor

#110 [refactor] 게시글 도메인 제목 필드 삭제
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/dto/PostRequest.java
  src/main/java/com/server/nodak/domain/post/dto/PostResponse.java
  src/main/java/com/server/nodak/domain/post/dto/PostSearchResponse.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/test/java/com/server/nodak/domain/comment/service/CommentServiceTest.java
  src/test/java/com/server/nodak/domain/post/controller/PostControllerTest.java
  src/test/java/com/server/nodak/domain/post/domain/PostTest.java
  src/test/java/com/server/nodak/domain/post/repository/PostRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/vote/utils/Utils.java
Labels: refactor

#112 [refactor] 게시글 등록 API 리팩토링
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/dto/PostRequest.java
  src/main/java/com/server/nodak/domain/post/dto/PostResponse.java
  src/main/java/com/server/nodak/domain/post/dto/PostSearchResponse.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/main/java/com/server/nodak/domain/vote/domain/Vote.java
  src/test/java/com/server/nodak/domain/post/controller/PostControllerTest.java
  src/test/java/com/server/nodak/domain/post/domain/PostTest.java
  src/test/java/com/server/nodak/domain/post/repository/PostRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
  src/test/java/com/server/nodak/domain/vote/utils/Utils.java
Labels: refactor

#114 게시글 조회 API 수정
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/dto/PostSearchResponse.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/vote/domain/VoteOption.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteOptionDetailResult.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteOptionListResult.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResponse.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResult.java
  src/main/java/com/server/nodak/domain/vote/repository/vote/VoteRepositoryImpl.java
  src/test/java/com/server/nodak/domain/post/controller/PostControllerTest.java
  src/test/java/com/server/nodak/domain/vote/service/VoteServiceTest.java
Labels: refactor

#116 회원조회 API 리팩토링
  src/main/java/com/server/nodak/domain/post/repository/PostRepository.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/server/nodak/domain/user/service/UserService.java
Labels: refactor

#120 [DOCS] 리드미에 시스템 아키첵처, ERD, API 명세서 추가
  README.md
Labels: documentation

#119 대댓글 여부에 따라, 댓글 삭제 로직 변경
  src/main/java/com/server/nodak/domain/comment/domain/Comment.java
  src/main/java/com/server/nodak/domain/comment/service/CommentService.java
  src/main/java/com/server/nodak/domain/reply/controller/ReplyController.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyJpaRepository.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyRepository.java
  src/main/java/com/server/nodak/domain/reply/repository/ReplyRepositoryImpl.java
  src/test/java/com/server/nodak/domain/comment/service/CommentServiceTest.java
Labels: 기능 구현
