Repository nodak-v2/Nodak-Server, pull requests merged in 2024-05, with the labels that each got.

#24 [Feat] Vote 도메인 Dao 구현 및 테스트
  src/main/java/com/server/nodak/domain/vote/dto/VoteOptionResult.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResult.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResultResponse.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteHistoryRepository.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteOptionRepository.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepository.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepositoryImpl.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteHistoryRepositoryTest.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteOptionRepositoryTests.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteRepositoryTest.java
Labels: 기능 구현, 테스트

#26 feat : 권한 체크 aop 기능 구현
  src/main/java/com/server/nodak/exception/common/AuthorizationException.java
  src/main/java/com/server/nodak/security/aop/AuthorizationAop.java
  src/main/java/com/server/nodak/security/aop/AuthorizationRequired.java
  src/test/java/com/server/nodak/security/aop/AuthorizationAopTest.java
Labels: 기능 구현, 테스트

#25 feat: Security 인증 서비스 구현
  src/main/java/com/server/nodak/exception/common/AuthorizationException.java
  src/main/java/com/server/nodak/security/NodakAuthentication.java
  src/main/java/com/server/nodak/security/SecurityServiceImpl.java
  src/main/java/com/server/nodak/security/StubSecurityService.java
  src/main/java/com/server/nodak/security/aop/AuthorizationAop.java
  src/main/java/com/server/nodak/security/aop/AuthorizationRequired.java
  src/test/java/com/server/nodak/security/SecurityServiceImplTest.java
  src/test/java/com/server/nodak/security/aop/AuthorizationAopTest.java
Labels: 기능 구현, 테스트

#27 [feat] Vote 도메인 Service 구현 및 테스트
  src/main/java/com/server/nodak/domain/vote/service/VoteService.java
  src/test/java/com/server/nodak/domain/vote/service/VoteServiceTest.java
Labels: 기능 구현, 테스트

#31 [feat] Vote 도메인 Controller 구현 및 테스트
  src/main/java/com/server/nodak/domain/vote/controller/VoteController.java
  src/main/java/com/server/nodak/global/common/response/ApiResponse.java
  src/main/java/com/server/nodak/global/config/SwaggerConfig.java
  src/test/java/com/server/nodak/domain/vote/controller/VoteControllerTest.java
Labels: 기능 구현, 테스트

#37 [feat] Security 유틸 클래스 기능 구현
  src/main/java/com/server/nodak/security/SecurityUtils.java
  src/test/java/com/server/nodak/security/SecurityUtilsTest.java
Labels: 기능 구현, 테스트

#36 feat : OAuth Security 설정 적용
  src/main/java/com/server/nodak/security/SecurityConfig.java
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: 기능 구현

#33 [feat] OAuth 성공/실패 핸들러 구현
  src/main/java/com/server/nodak/security/SecurityConfig.java
  src/main/java/com/server/nodak/security/oauth/handler/OAuthAuthenticationFailureHandler.java
  src/main/java/com/server/nodak/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/resources/application.yaml
  src/test/java/com/server/nodak/security/oauth/handler/OAuthAuthenticationFailureHandlerTest.java
  src/test/java/com/server/nodak/security/oauth/handler/OAuthAuthenticationSuccessHandlerTest.java
  src/test/resources/application.yaml
Labels: 기능 구현, 테스트

#45 [feat] PostService 구현
  src/main/java/com/server/nodak/domain/post/domain/StarPost.java
  src/main/java/com/server/nodak/domain/post/repository/StarPostRepository.java
  src/main/java/com/server/nodak/domain/post/service/PostService.java
  src/test/java/com/server/nodak/domain/post/repository/StarPostRepositoryTest.java
  src/test/java/com/server/nodak/domain/post/service/PostServiceTest.java
  src/test/java/com/server/nodak/domain/vote/utils/Utils.java
Labels: 기능 구현, 테스트

#48 [feat] : jwt 토큰 재발급 기능 구현
  src/main/java/com/server/nodak/security/jwt/JwtFilter.java
  src/test/java/com/server/nodak/security/jwt/JwtFilterTest.java
Labels: 기능 구현, 테스트

#46 [feat] PostController 및 Vote API 리팩토링
  src/main/java/com/server/nodak/domain/post/controller/PostController.java
  src/main/java/com/server/nodak/domain/vote/controller/VoteController.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteAfterResultResponse.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteBeforeResultResponse.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteOptionResult.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResponse.java
  src/main/java/com/server/nodak/domain/vote/dto/VoteResult.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepository.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/server/nodak/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/server/nodak/domain/vote/service/VoteService.java
  src/test/java/com/server/nodak/domain/post/controller/PostControllerTest.java
  src/test/java/com/server/nodak/domain/vote/controller/VoteControllerTest.java
  src/test/java/com/server/nodak/domain/vote/repository/VoteRepositoryImplTest.java
  src/test/java/com/server/nodak/domain/vote/service/VoteServiceTest.java
Labels: 기능 구현, 테스트, refactor

#51 Comment 도메인 API를 전반적으로 수정합니다.
  build.gradle
  src/main/java/com/server/nodak/domain/comment/controller/CommentController.java
  src/main/java/com/server/nodak/domain/comment/service/CommentService.java
  src/test/java/com/server/nodak/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/server/nodak/domain/comment/service/CommentServiceTest.java
Labels: 기능 구현, 테스트

#53 File API 컨트롤러 구현
  src/main/java/com/server/nodak/domain/s3/controller/S3Controller.java
  src/main/java/com/server/nodak/domain/s3/dto/DeleteImageRequest.java
  src/main/java/com/server/nodak/domain/s3/service/S3Service.java
  src/main/java/com/server/nodak/domain/s3/validator/ImagePath.java
  src/main/java/com/server/nodak/domain/s3/validator/PathValidator.java
  src/main/java/com/server/nodak/domain/s3/validator/ValidateImagePath.java
Labels: 기능 구현

#54 [feat] Security 익명 사용자 제거
  src/main/java/com/server/nodak/security/SecurityConfig.java
Labels: 기능 구현, 테스트

#59 [perform] VoteHistory 테이블 인덱스 최적화
  src/test/java/com/server/nodak/domain/vote/perform/VoteHistoryIndexOptimizeTest.java
  src/test/resources/application-perform.yaml
Labels: 테스트, 성능최적화

#61 feat : 유저 상태 도메인 및 Repository 구현
  src/main/java/com/server/nodak/domain/userstatus/domain/UserStatus.java
  src/main/java/com/server/nodak/domain/userstatus/dto/UserStatusResponse.java
  src/main/java/com/server/nodak/domain/userstatus/repository/InMemoryUserStatusRepository.java
  src/main/java/com/server/nodak/domain/userstatus/repository/UserStatusRepository.java
  src/main/java/com/server/nodak/domain/userstatus/service/UserStatusService.java
Labels: 기능 구현

#63 feat : user info service 코드 작성
  src/main/java/com/server/nodak/domain/user/dto/UserInfoResponse.java
  src/main/java/com/server/nodak/domain/user/service/UserService.java
  src/main/java/com/server/nodak/security/SecurityUtils.java
  src/test/java/com/server/nodak/domain/user/service/UserServiceTest.java
  src/test/java/com/server/nodak/security/SecurityUtilsTest.java
Labels: 기능 구현, 테스트
