Repository nodak-v2/Nodak-Server, pull requests merged in 2024-04, with the labels that each got.

#6 queryDSL 설정을 추가합니다.
  .gitignore
  build.gradle
  src/main/resources/application.yaml
Labels: 프로젝트 설정

#8 [Feat] 유저 엔티티 클래스 구현
  src/main/java/com/server/nodak/NodakApplication.java
  src/main/java/com/server/nodak/domain/user/domain/User.java
  src/main/java/com/server/nodak/domain/user/domain/UserProvider.java
  src/main/java/com/server/nodak/domain/user/domain/UserRole.java
  src/test/java/com/server/nodak/domain/user/domain/UserTest.java
Labels: 기능 구현, 테스트

#10 공통 예외 클래스 및 핸들러를 구현합니다.
  src/main/java/com/server/nodak/exception/BaseErrorResponse.java
  src/main/java/com/server/nodak/exception/GlobalExceptionHandler.java
  src/main/java/com/server/nodak/exception/common/BaseException.java
  src/main/java/com/server/nodak/exception/common/ConflictException.java
  src/main/java/com/server/nodak/exception/common/DataNotFoundException.java
  src/main/java/com/server/nodak/exception/common/InternalServerErrorException.java
Labels: 기능 구현

#5 [Feat] 투표 도메인 엔티티 임시 구현
  build.gradle
  src/main/java/com/server/nodak/NodakApplication.java
  src/main/java/com/server/nodak/domain/vote/domain/Vote.java
  src/main/java/com/server/nodak/domain/vote/domain/VoteHistory.java
  src/main/java/com/server/nodak/domain/vote/domain/VoteOption.java
  src/test/java/com/server/nodak/domain/vote/domain/VoteOptionTest.java
  src/test/java/com/server/nodak/domain/vote/domain/VoteTest.java
  src/test/java/com/server/nodak/domain/vote/utils/Utils.java
Labels: 기능 구현, 테스트

#13 [refact] 중복된 어노테이션이 있어 삭제했습니다.
  src/main/java/com/server/nodak/NodakApplication.java
Labels: refactor

#15 [Feat] Swagger 적용
  build.gradle
  src/main/java/com/server/nodak/global/config/SwaggerConfig.java
  src/main/resources/application.yaml
Labels: 프로젝트 설정

#11 [Feat] JWT 기능 구현
  build.gradle
  src/main/java/com/server/nodak/security/jwt/JwtProperties.java
  src/main/java/com/server/nodak/security/jwt/TokenProvider.java
  src/test/java/com/server/nodak/security/jwt/TokenProviderTest.java
  src/test/resources/application.yaml
Labels: 기능 구현, 테스트

#16 [Feat] 게시글, 카테고리, 댓글 엔티티 구현
  src/main/java/com/server/nodak/domain/comment/domain/Comment.java
  src/main/java/com/server/nodak/domain/post/domain/Category.java
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/domain/StarPost.java
  src/main/java/com/server/nodak/domain/user/domain/User.java
  src/test/java/com/server/nodak/domain/post/domain/PostTest.java
  src/test/java/com/server/nodak/domain/user/domain/UserTest.java
Labels: 기능 구현

#18 feat : httpservlet utils 기능 작성 (#1)
  src/main/java/com/server/nodak/utils/HttpServletUtils.java
  src/test/java/com/server/nodak/utils/HttpServletUtilsTest.java
Labels: 기능 구현, 테스트

#19 [feat] 유저 레포지토리 구현 입니다.
  src/main/java/com/server/nodak/domain/user/repository/UserJpaRepository.java
  src/main/java/com/server/nodak/domain/user/repository/UserRepository.java
  src/main/java/com/server/nodak/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/server/nodak/domain/user/repository/UserRepositoryImplTest.java
Labels: 기능 구현, 테스트

#21 [Feat] 댓글 API 구현 및 테스트
  src/main/java/com/server/nodak/config/QueryDslConfiguration.java
  src/main/java/com/server/nodak/domain/comment/controller/CommentController.java
  src/main/java/com/server/nodak/domain/comment/domain/Comment.java
  src/main/java/com/server/nodak/domain/comment/dto/request/CreateCommentRequest.java
  src/main/java/com/server/nodak/domain/comment/dto/request/UpdateCommentRequest.java
  src/main/java/com/server/nodak/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentQueryRepository.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentRepository.java
  src/main/java/com/server/nodak/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/server/nodak/domain/comment/service/CommentService.java
  src/main/java/com/server/nodak/domain/post/domain/Category.java
  src/main/java/com/server/nodak/domain/post/domain/Post.java
  src/main/java/com/server/nodak/domain/post/domain/StarPost.java
  src/main/java/com/server/nodak/domain/post/repository/CategoryJpaRepository.java
  src/main/java/com/server/nodak/domain/post/repository/CategoryRepository.java
  src/main/java/com/server/nodak/domain/post/repository/PostJpaRepository.java
  src/main/java/com/server/nodak/domain/post/repository/PostRepository.java
  src/main/java/com/server/nodak/exception/common/BadRequestException.java
  src/test/java/com/server/nodak/domain/comment/service/CommentServiceTest.java
Labels: 기능 구현, 테스트
